# Generated by Django 4.1.5 on 2023-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
