# Generated by Django 4.1.5 on 2023-01-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_slide_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='live',
            new_name='is_live',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='public',
            new_name='is_public',
        ),
    ]
