# Generated by Django 4.1.5 on 2023-01-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_alter_slide_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
