# Generated by Django 4.1.5 on 2023-01-29 13:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0006_alter_slide_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='slide'),
        ),
    ]
