# Generated by Django 4.1.5 on 2023-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0007_alter_slide_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
