# Generated by Django 4.1.5 on 2023-02-01 11:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0008_slide_file_alter_slide_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='file',
        ),
        migrations.AddField(
            model_name='slide',
            name='slide',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
