# Generated by Django 4.1.5 on 2023-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0009_remove_slide_file_slide_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='is_live',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='slide',
            name='is_public',
            field=models.BooleanField(),
        ),
    ]
