# Generated by Django 4.1.5 on 2023-02-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0010_alter_slide_is_live_alter_slide_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='user',
            new_name='users',
        ),
    ]
