# Generated by Django 4.1.5 on 2023-02-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slides', '0014_slide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
