# Generated by Django 4.1.5 on 2023-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='http://seekpng.com/png/full/110-1100707_person-avatar-placeholder.png'),
        ),
    ]
