# Generated by Django 4.1.5 on 2023-01-29 12:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default=users.models.User.get_default_avatar),
        ),
    ]
