# Generated by Django 4.1.5 on 2023-02-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0010_alter_slide_is_live_alter_slide_is_public'),
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slides',
            field=models.ManyToManyField(related_name='users', to='slides.slide'),
        ),
    ]
