# Generated by Django 4.1.5 on 2023-02-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0011_rename_user_slide_users'),
        ('users', '0006_user_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slides',
            field=models.ManyToManyField(related_name='user', to='slides.slide'),
        ),
    ]
