# Generated by Django 4.1.5 on 2023-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0012_remove_slide_users_slide_user'),
        ('users', '0007_alter_user_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slides',
            field=models.ManyToManyField(related_name='users', to='slides.slide'),
        ),
    ]
