# Generated by Django 4.1.5 on 2023-02-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0013_remove_slide_user'),
        ('users', '0008_alter_user_slides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slides',
        ),
        migrations.AddField(
            model_name='user',
            name='slides',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slides.slide'),
        ),
    ]
